apiVersion: v1
kind: Namespace
metadata:
  name: ate-manual-test
---
apiVersion: ate.dev/v1alpha1
kind: WorkerPool
metadata:
  name: sandbox-pool
  namespace: ate-manual-test
  labels:
    workload: sandbox
spec:
  replicas: 1
  ateomImage: ko://github.com/agent-substrate/substrate/cmd/ateom-gvisor
---
apiVersion: ate.dev/v1alpha1
kind: ActorTemplate
metadata:
  name: sandbox-template
  namespace: ate-manual-test
spec:
  workerSelector:
    matchLabels:
      workload: sandbox
  pauseImage: "registry.k8s.io/pause:3.10.2@sha256:f548e0e8e3dc1896ca956272154dde3314e8cc4fde0a57577ee9fa1c63f5baf4"
  containers:
  - name: sandbox
    image: ko://github.com/agent-substrate/substrate/demos/sandbox
    command: ["/ko-app/sandbox"]
    env:
    - name: PORT
      value: "80"
    volumeMounts:
    - name: external-data
      mountPath: /external-data
  snapshotsConfig:
    location: gs://ate-snapshots/ate-manual-test/
  volumes:
  - name: external-data
    externalVolumeTemplate:
      capacity: 1Gi
      storageClassName: csi-hostpath-sc
