// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: atelet.proto

package ateletpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckpointType int32

const (
	// Should never happen
	CheckpointType_CHECKPOINT_TYPE_UNSPECIFIED CheckpointType = 0
	// Save snapshot only in local filesystem
	CheckpointType_CHECKPOINT_TYPE_LOCAL CheckpointType = 1
	// Save snapshot to object storage
	CheckpointType_CHECKPOINT_TYPE_EXTERNAL CheckpointType = 2
)

// Enum value maps for CheckpointType.
var (
	CheckpointType_name = map[int32]string{
		0: "CHECKPOINT_TYPE_UNSPECIFIED",
		1: "CHECKPOINT_TYPE_LOCAL",
		2: "CHECKPOINT_TYPE_EXTERNAL",
	}
	CheckpointType_value = map[string]int32{
		"CHECKPOINT_TYPE_UNSPECIFIED": 0,
		"CHECKPOINT_TYPE_LOCAL":       1,
		"CHECKPOINT_TYPE_EXTERNAL":    2,
	}
)

func (x CheckpointType) Enum() *CheckpointType {
	p := new(CheckpointType)
	*p = x
	return p
}

func (x CheckpointType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckpointType) Descriptor() protoreflect.EnumDescriptor {
	return file_atelet_proto_enumTypes[0].Descriptor()
}

func (CheckpointType) Type() protoreflect.EnumType {
	return &file_atelet_proto_enumTypes[0]
}

func (x CheckpointType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckpointType.Descriptor instead.
func (CheckpointType) EnumDescriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{0}
}

type RunRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TargetAteomUid         string                 `protobuf:"bytes,1,opt,name=target_ateom_uid,json=targetAteomUid,proto3" json:"target_ateom_uid,omitempty"`
	ActorTemplateNamespace string                 `protobuf:"bytes,3,opt,name=actor_template_namespace,json=actorTemplateNamespace,proto3" json:"actor_template_namespace,omitempty"`
	ActorTemplateName      string                 `protobuf:"bytes,4,opt,name=actor_template_name,json=actorTemplateName,proto3" json:"actor_template_name,omitempty"`
	ActorId                string                 `protobuf:"bytes,5,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Runsc                  *RunscConfig           `protobuf:"bytes,8,opt,name=runsc,proto3" json:"runsc,omitempty"`
	Spec                   *WorkloadSpec          `protobuf:"bytes,7,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_atelet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetTargetAteomUid() string {
	if x != nil {
		return x.TargetAteomUid
	}
	return ""
}

func (x *RunRequest) GetActorTemplateNamespace() string {
	if x != nil {
		return x.ActorTemplateNamespace
	}
	return ""
}

func (x *RunRequest) GetActorTemplateName() string {
	if x != nil {
		return x.ActorTemplateName
	}
	return ""
}

func (x *RunRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *RunRequest) GetRunsc() *RunscConfig {
	if x != nil {
		return x.Runsc
	}
	return nil
}

func (x *RunRequest) GetSpec() *WorkloadSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type GCPAuthenticationConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Use           bool                   `protobuf:"varint,1,opt,name=use,proto3" json:"use,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GCPAuthenticationConfig) Reset() {
	*x = GCPAuthenticationConfig{}
	mi := &file_atelet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCPAuthenticationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCPAuthenticationConfig) ProtoMessage() {}

func (x *GCPAuthenticationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCPAuthenticationConfig.ProtoReflect.Descriptor instead.
func (*GCPAuthenticationConfig) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{1}
}

func (x *GCPAuthenticationConfig) GetUse() bool {
	if x != nil {
		return x.Use
	}
	return false
}

type AuthenticationConfig struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Gcp           *GCPAuthenticationConfig `protobuf:"bytes,1,opt,name=gcp,proto3" json:"gcp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationConfig) Reset() {
	*x = AuthenticationConfig{}
	mi := &file_atelet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationConfig) ProtoMessage() {}

func (x *AuthenticationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationConfig.ProtoReflect.Descriptor instead.
func (*AuthenticationConfig) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{2}
}

func (x *AuthenticationConfig) GetGcp() *GCPAuthenticationConfig {
	if x != nil {
		return x.Gcp
	}
	return nil
}

type RunscPlatformConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Check the downloaded binary against this hash.  Also used for naming the
	// downloaded file to prevent collisions.
	Sha256Hash string `protobuf:"bytes,1,opt,name=sha256_hash,json=sha256Hash,proto3" json:"sha256_hash,omitempty"`
	// gs:// URL to download the runsc binary.
	Url           string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunscPlatformConfig) Reset() {
	*x = RunscPlatformConfig{}
	mi := &file_atelet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunscPlatformConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunscPlatformConfig) ProtoMessage() {}

func (x *RunscPlatformConfig) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunscPlatformConfig.ProtoReflect.Descriptor instead.
func (*RunscPlatformConfig) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{3}
}

func (x *RunscPlatformConfig) GetSha256Hash() string {
	if x != nil {
		return x.Sha256Hash
	}
	return ""
}

func (x *RunscPlatformConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type RunscConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Amd64 *RunscPlatformConfig   `protobuf:"bytes,1,opt,name=amd64,proto3" json:"amd64,omitempty"`
	Arm64 *RunscPlatformConfig   `protobuf:"bytes,2,opt,name=arm64,proto3" json:"arm64,omitempty"`
	// How should atelet authenticate to fetch the runsc binary?
	Authentication *AuthenticationConfig `protobuf:"bytes,3,opt,name=authentication,proto3" json:"authentication,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunscConfig) Reset() {
	*x = RunscConfig{}
	mi := &file_atelet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunscConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunscConfig) ProtoMessage() {}

func (x *RunscConfig) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunscConfig.ProtoReflect.Descriptor instead.
func (*RunscConfig) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{4}
}

func (x *RunscConfig) GetAmd64() *RunscPlatformConfig {
	if x != nil {
		return x.Amd64
	}
	return nil
}

func (x *RunscConfig) GetArm64() *RunscPlatformConfig {
	if x != nil {
		return x.Arm64
	}
	return nil
}

func (x *RunscConfig) GetAuthentication() *AuthenticationConfig {
	if x != nil {
		return x.Authentication
	}
	return nil
}

// WorkloadSpec parallels Pod, but with far fewer configurable fields.
type WorkloadSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*Container           `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	PauseImage    string                 `protobuf:"bytes,2,opt,name=pause_image,json=pauseImage,proto3" json:"pause_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadSpec) Reset() {
	*x = WorkloadSpec{}
	mi := &file_atelet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadSpec) ProtoMessage() {}

func (x *WorkloadSpec) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadSpec.ProtoReflect.Descriptor instead.
func (*WorkloadSpec) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{5}
}

func (x *WorkloadSpec) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *WorkloadSpec) GetPauseImage() string {
	if x != nil {
		return x.PauseImage
	}
	return ""
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Command       []string               `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	Env           []*EnvEntry            `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_atelet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{6}
}

func (x *Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Container) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Container) GetEnv() []*EnvEntry {
	if x != nil {
		return x.Env
	}
	return nil
}

type EnvEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvEntry) Reset() {
	*x = EnvEntry{}
	mi := &file_atelet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvEntry) ProtoMessage() {}

func (x *EnvEntry) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvEntry.ProtoReflect.Descriptor instead.
func (*EnvEntry) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{7}
}

func (x *EnvEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_atelet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{8}
}

type LocalCheckpointConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A sub-directory on the local filesystem below which the checkpoint data will be
	// stored.  The structure of the checkpoint should generally be treated as opaque.
	SnapshotPrefix string `protobuf:"bytes,1,opt,name=snapshot_prefix,json=snapshotPrefix,proto3" json:"snapshot_prefix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LocalCheckpointConfiguration) Reset() {
	*x = LocalCheckpointConfiguration{}
	mi := &file_atelet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalCheckpointConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalCheckpointConfiguration) ProtoMessage() {}

func (x *LocalCheckpointConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalCheckpointConfiguration.ProtoReflect.Descriptor instead.
func (*LocalCheckpointConfiguration) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{9}
}

func (x *LocalCheckpointConfiguration) GetSnapshotPrefix() string {
	if x != nil {
		return x.SnapshotPrefix
	}
	return ""
}

type ExternalCheckpointConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An object storage URI prefix below which the checkpoint data will be
	// stored.
	//
	// The structure of the checkpoint should generally be treated as opaque. For
	// gVisor, the checkpoint consists of a checkpoint.img file that contains the
	// memory, sentry state, and filesystem deltas.  ateom will write additional
	// files to store the WorkloadSpec, which must be reassembled before gVisor
	// can restore a checkpoint.
	//
	// For example: "gs://bucket/actors/1234/snapshots/5678/"
	SnapshotUriPrefix string `protobuf:"bytes,1,opt,name=snapshot_uri_prefix,json=snapshotUriPrefix,proto3" json:"snapshot_uri_prefix,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExternalCheckpointConfiguration) Reset() {
	*x = ExternalCheckpointConfiguration{}
	mi := &file_atelet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalCheckpointConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalCheckpointConfiguration) ProtoMessage() {}

func (x *ExternalCheckpointConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalCheckpointConfiguration.ProtoReflect.Descriptor instead.
func (*ExternalCheckpointConfiguration) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{10}
}

func (x *ExternalCheckpointConfiguration) GetSnapshotUriPrefix() string {
	if x != nil {
		return x.SnapshotUriPrefix
	}
	return ""
}

type CheckpointRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TargetAteomUid         string                 `protobuf:"bytes,1,opt,name=target_ateom_uid,json=targetAteomUid,proto3" json:"target_ateom_uid,omitempty"`
	ActorTemplateNamespace string                 `protobuf:"bytes,3,opt,name=actor_template_namespace,json=actorTemplateNamespace,proto3" json:"actor_template_namespace,omitempty"`
	ActorTemplateName      string                 `protobuf:"bytes,4,opt,name=actor_template_name,json=actorTemplateName,proto3" json:"actor_template_name,omitempty"`
	ActorId                string                 `protobuf:"bytes,5,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Runsc                  *RunscConfig           `protobuf:"bytes,6,opt,name=runsc,proto3" json:"runsc,omitempty"`
	Spec                   *WorkloadSpec          `protobuf:"bytes,7,opt,name=spec,proto3" json:"spec,omitempty"`
	Type                   CheckpointType         `protobuf:"varint,9,opt,name=type,proto3,enum=atelet.CheckpointType" json:"type,omitempty"`
	// The checkpoint configuration, depending on the type.
	//
	// Types that are valid to be assigned to Config:
	//
	//	*CheckpointRequest_LocalConfig
	//	*CheckpointRequest_ExternalConfig
	Config        isCheckpointRequest_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointRequest) Reset() {
	*x = CheckpointRequest{}
	mi := &file_atelet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointRequest) ProtoMessage() {}

func (x *CheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointRequest.ProtoReflect.Descriptor instead.
func (*CheckpointRequest) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{11}
}

func (x *CheckpointRequest) GetTargetAteomUid() string {
	if x != nil {
		return x.TargetAteomUid
	}
	return ""
}

func (x *CheckpointRequest) GetActorTemplateNamespace() string {
	if x != nil {
		return x.ActorTemplateNamespace
	}
	return ""
}

func (x *CheckpointRequest) GetActorTemplateName() string {
	if x != nil {
		return x.ActorTemplateName
	}
	return ""
}

func (x *CheckpointRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *CheckpointRequest) GetRunsc() *RunscConfig {
	if x != nil {
		return x.Runsc
	}
	return nil
}

func (x *CheckpointRequest) GetSpec() *WorkloadSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *CheckpointRequest) GetType() CheckpointType {
	if x != nil {
		return x.Type
	}
	return CheckpointType_CHECKPOINT_TYPE_UNSPECIFIED
}

func (x *CheckpointRequest) GetConfig() isCheckpointRequest_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CheckpointRequest) GetLocalConfig() *LocalCheckpointConfiguration {
	if x != nil {
		if x, ok := x.Config.(*CheckpointRequest_LocalConfig); ok {
			return x.LocalConfig
		}
	}
	return nil
}

func (x *CheckpointRequest) GetExternalConfig() *ExternalCheckpointConfiguration {
	if x != nil {
		if x, ok := x.Config.(*CheckpointRequest_ExternalConfig); ok {
			return x.ExternalConfig
		}
	}
	return nil
}

type isCheckpointRequest_Config interface {
	isCheckpointRequest_Config()
}

type CheckpointRequest_LocalConfig struct {
	LocalConfig *LocalCheckpointConfiguration `protobuf:"bytes,10,opt,name=local_config,json=localConfig,proto3,oneof"`
}

type CheckpointRequest_ExternalConfig struct {
	ExternalConfig *ExternalCheckpointConfiguration `protobuf:"bytes,11,opt,name=external_config,json=externalConfig,proto3,oneof"`
}

func (*CheckpointRequest_LocalConfig) isCheckpointRequest_Config() {}

func (*CheckpointRequest_ExternalConfig) isCheckpointRequest_Config() {}

type CheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointResponse) Reset() {
	*x = CheckpointResponse{}
	mi := &file_atelet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointResponse) ProtoMessage() {}

func (x *CheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointResponse.ProtoReflect.Descriptor instead.
func (*CheckpointResponse) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{12}
}

type RestoreRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TargetAteomUid         string                 `protobuf:"bytes,1,opt,name=target_ateom_uid,json=targetAteomUid,proto3" json:"target_ateom_uid,omitempty"`
	ActorTemplateNamespace string                 `protobuf:"bytes,3,opt,name=actor_template_namespace,json=actorTemplateNamespace,proto3" json:"actor_template_namespace,omitempty"`
	ActorTemplateName      string                 `protobuf:"bytes,4,opt,name=actor_template_name,json=actorTemplateName,proto3" json:"actor_template_name,omitempty"`
	ActorId                string                 `protobuf:"bytes,5,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Runsc                  *RunscConfig           `protobuf:"bytes,6,opt,name=runsc,proto3" json:"runsc,omitempty"`
	Spec                   *WorkloadSpec          `protobuf:"bytes,7,opt,name=spec,proto3" json:"spec,omitempty"`
	Type                   CheckpointType         `protobuf:"varint,9,opt,name=type,proto3,enum=atelet.CheckpointType" json:"type,omitempty"`
	// The checkpoint configuration, depending on the type.
	//
	// Types that are valid to be assigned to Config:
	//
	//	*RestoreRequest_LocalConfig
	//	*RestoreRequest_ExternalConfig
	Config        isRestoreRequest_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_atelet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{13}
}

func (x *RestoreRequest) GetTargetAteomUid() string {
	if x != nil {
		return x.TargetAteomUid
	}
	return ""
}

func (x *RestoreRequest) GetActorTemplateNamespace() string {
	if x != nil {
		return x.ActorTemplateNamespace
	}
	return ""
}

func (x *RestoreRequest) GetActorTemplateName() string {
	if x != nil {
		return x.ActorTemplateName
	}
	return ""
}

func (x *RestoreRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *RestoreRequest) GetRunsc() *RunscConfig {
	if x != nil {
		return x.Runsc
	}
	return nil
}

func (x *RestoreRequest) GetSpec() *WorkloadSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *RestoreRequest) GetType() CheckpointType {
	if x != nil {
		return x.Type
	}
	return CheckpointType_CHECKPOINT_TYPE_UNSPECIFIED
}

func (x *RestoreRequest) GetConfig() isRestoreRequest_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RestoreRequest) GetLocalConfig() *LocalCheckpointConfiguration {
	if x != nil {
		if x, ok := x.Config.(*RestoreRequest_LocalConfig); ok {
			return x.LocalConfig
		}
	}
	return nil
}

func (x *RestoreRequest) GetExternalConfig() *ExternalCheckpointConfiguration {
	if x != nil {
		if x, ok := x.Config.(*RestoreRequest_ExternalConfig); ok {
			return x.ExternalConfig
		}
	}
	return nil
}

type isRestoreRequest_Config interface {
	isRestoreRequest_Config()
}

type RestoreRequest_LocalConfig struct {
	LocalConfig *LocalCheckpointConfiguration `protobuf:"bytes,10,opt,name=local_config,json=localConfig,proto3,oneof"`
}

type RestoreRequest_ExternalConfig struct {
	ExternalConfig *ExternalCheckpointConfiguration `protobuf:"bytes,11,opt,name=external_config,json=externalConfig,proto3,oneof"`
}

func (*RestoreRequest_LocalConfig) isRestoreRequest_Config() {}

func (*RestoreRequest_ExternalConfig) isRestoreRequest_Config() {}

type RestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_atelet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atelet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_atelet_proto_rawDescGZIP(), []int{14}
}

var File_atelet_proto protoreflect.FileDescriptor

const file_atelet_proto_rawDesc = "" +
	"\n" +
	"\fatelet.proto\x12\x06atelet\"\x90\x02\n" +
	"\n" +
	"RunRequest\x12(\n" +
	"\x10target_ateom_uid\x18\x01 \x01(\tR\x0etargetAteomUid\x128\n" +
	"\x18actor_template_namespace\x18\x03 \x01(\tR\x16actorTemplateNamespace\x12.\n" +
	"\x13actor_template_name\x18\x04 \x01(\tR\x11actorTemplateName\x12\x19\n" +
	"\bactor_id\x18\x05 \x01(\tR\aactorId\x12)\n" +
	"\x05runsc\x18\b \x01(\v2\x13.atelet.RunscConfigR\x05runsc\x12(\n" +
	"\x04spec\x18\a \x01(\v2\x14.atelet.WorkloadSpecR\x04spec\"+\n" +
	"\x17GCPAuthenticationConfig\x12\x10\n" +
	"\x03use\x18\x01 \x01(\bR\x03use\"I\n" +
	"\x14AuthenticationConfig\x121\n" +
	"\x03gcp\x18\x01 \x01(\v2\x1f.atelet.GCPAuthenticationConfigR\x03gcp\"H\n" +
	"\x13RunscPlatformConfig\x12\x1f\n" +
	"\vsha256_hash\x18\x01 \x01(\tR\n" +
	"sha256Hash\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\xb9\x01\n" +
	"\vRunscConfig\x121\n" +
	"\x05amd64\x18\x01 \x01(\v2\x1b.atelet.RunscPlatformConfigR\x05amd64\x121\n" +
	"\x05arm64\x18\x02 \x01(\v2\x1b.atelet.RunscPlatformConfigR\x05arm64\x12D\n" +
	"\x0eauthentication\x18\x03 \x01(\v2\x1c.atelet.AuthenticationConfigR\x0eauthentication\"b\n" +
	"\fWorkloadSpec\x121\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x11.atelet.ContainerR\n" +
	"containers\x12\x1f\n" +
	"\vpause_image\x18\x02 \x01(\tR\n" +
	"pauseImage\"s\n" +
	"\tContainer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12\"\n" +
	"\x03env\x18\x04 \x03(\v2\x10.atelet.EnvEntryR\x03env\"4\n" +
	"\bEnvEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\r\n" +
	"\vRunResponse\"G\n" +
	"\x1cLocalCheckpointConfiguration\x12'\n" +
	"\x0fsnapshot_prefix\x18\x01 \x01(\tR\x0esnapshotPrefix\"Q\n" +
	"\x1fExternalCheckpointConfiguration\x12.\n" +
	"\x13snapshot_uri_prefix\x18\x01 \x01(\tR\x11snapshotUriPrefix\"\xf2\x03\n" +
	"\x11CheckpointRequest\x12(\n" +
	"\x10target_ateom_uid\x18\x01 \x01(\tR\x0etargetAteomUid\x128\n" +
	"\x18actor_template_namespace\x18\x03 \x01(\tR\x16actorTemplateNamespace\x12.\n" +
	"\x13actor_template_name\x18\x04 \x01(\tR\x11actorTemplateName\x12\x19\n" +
	"\bactor_id\x18\x05 \x01(\tR\aactorId\x12)\n" +
	"\x05runsc\x18\x06 \x01(\v2\x13.atelet.RunscConfigR\x05runsc\x12(\n" +
	"\x04spec\x18\a \x01(\v2\x14.atelet.WorkloadSpecR\x04spec\x12*\n" +
	"\x04type\x18\t \x01(\x0e2\x16.atelet.CheckpointTypeR\x04type\x12I\n" +
	"\flocal_config\x18\n" +
	" \x01(\v2$.atelet.LocalCheckpointConfigurationH\x00R\vlocalConfig\x12R\n" +
	"\x0fexternal_config\x18\v \x01(\v2'.atelet.ExternalCheckpointConfigurationH\x00R\x0eexternalConfigB\b\n" +
	"\x06configJ\x04\b\b\x10\t\"\x14\n" +
	"\x12CheckpointResponse\"\xef\x03\n" +
	"\x0eRestoreRequest\x12(\n" +
	"\x10target_ateom_uid\x18\x01 \x01(\tR\x0etargetAteomUid\x128\n" +
	"\x18actor_template_namespace\x18\x03 \x01(\tR\x16actorTemplateNamespace\x12.\n" +
	"\x13actor_template_name\x18\x04 \x01(\tR\x11actorTemplateName\x12\x19\n" +
	"\bactor_id\x18\x05 \x01(\tR\aactorId\x12)\n" +
	"\x05runsc\x18\x06 \x01(\v2\x13.atelet.RunscConfigR\x05runsc\x12(\n" +
	"\x04spec\x18\a \x01(\v2\x14.atelet.WorkloadSpecR\x04spec\x12*\n" +
	"\x04type\x18\t \x01(\x0e2\x16.atelet.CheckpointTypeR\x04type\x12I\n" +
	"\flocal_config\x18\n" +
	" \x01(\v2$.atelet.LocalCheckpointConfigurationH\x00R\vlocalConfig\x12R\n" +
	"\x0fexternal_config\x18\v \x01(\v2'.atelet.ExternalCheckpointConfigurationH\x00R\x0eexternalConfigB\b\n" +
	"\x06configJ\x04\b\b\x10\t\"\x11\n" +
	"\x0fRestoreResponse*j\n" +
	"\x0eCheckpointType\x12\x1f\n" +
	"\x1bCHECKPOINT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CHECKPOINT_TYPE_LOCAL\x10\x01\x12\x1c\n" +
	"\x18CHECKPOINT_TYPE_EXTERNAL\x10\x022\xc4\x01\n" +
	"\vAteomHerder\x120\n" +
	"\x03Run\x12\x12.atelet.RunRequest\x1a\x13.atelet.RunResponse\"\x00\x12E\n" +
	"\n" +
	"Checkpoint\x12\x19.atelet.CheckpointRequest\x1a\x1a.atelet.CheckpointResponse\"\x00\x12<\n" +
	"\aRestore\x12\x16.atelet.RestoreRequest\x1a\x17.atelet.RestoreResponse\"\x00B>Z<github.com/agent-substrate/substrate/internal/proto/ateletpbb\x06proto3"

var (
	file_atelet_proto_rawDescOnce sync.Once
	file_atelet_proto_rawDescData []byte
)

func file_atelet_proto_rawDescGZIP() []byte {
	file_atelet_proto_rawDescOnce.Do(func() {
		file_atelet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atelet_proto_rawDesc), len(file_atelet_proto_rawDesc)))
	})
	return file_atelet_proto_rawDescData
}

var file_atelet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_atelet_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_atelet_proto_goTypes = []any{
	(CheckpointType)(0),                     // 0: atelet.CheckpointType
	(*RunRequest)(nil),                      // 1: atelet.RunRequest
	(*GCPAuthenticationConfig)(nil),         // 2: atelet.GCPAuthenticationConfig
	(*AuthenticationConfig)(nil),            // 3: atelet.AuthenticationConfig
	(*RunscPlatformConfig)(nil),             // 4: atelet.RunscPlatformConfig
	(*RunscConfig)(nil),                     // 5: atelet.RunscConfig
	(*WorkloadSpec)(nil),                    // 6: atelet.WorkloadSpec
	(*Container)(nil),                       // 7: atelet.Container
	(*EnvEntry)(nil),                        // 8: atelet.EnvEntry
	(*RunResponse)(nil),                     // 9: atelet.RunResponse
	(*LocalCheckpointConfiguration)(nil),    // 10: atelet.LocalCheckpointConfiguration
	(*ExternalCheckpointConfiguration)(nil), // 11: atelet.ExternalCheckpointConfiguration
	(*CheckpointRequest)(nil),               // 12: atelet.CheckpointRequest
	(*CheckpointResponse)(nil),              // 13: atelet.CheckpointResponse
	(*RestoreRequest)(nil),                  // 14: atelet.RestoreRequest
	(*RestoreResponse)(nil),                 // 15: atelet.RestoreResponse
}
var file_atelet_proto_depIdxs = []int32{
	5,  // 0: atelet.RunRequest.runsc:type_name -> atelet.RunscConfig
	6,  // 1: atelet.RunRequest.spec:type_name -> atelet.WorkloadSpec
	2,  // 2: atelet.AuthenticationConfig.gcp:type_name -> atelet.GCPAuthenticationConfig
	4,  // 3: atelet.RunscConfig.amd64:type_name -> atelet.RunscPlatformConfig
	4,  // 4: atelet.RunscConfig.arm64:type_name -> atelet.RunscPlatformConfig
	3,  // 5: atelet.RunscConfig.authentication:type_name -> atelet.AuthenticationConfig
	7,  // 6: atelet.WorkloadSpec.containers:type_name -> atelet.Container
	8,  // 7: atelet.Container.env:type_name -> atelet.EnvEntry
	5,  // 8: atelet.CheckpointRequest.runsc:type_name -> atelet.RunscConfig
	6,  // 9: atelet.CheckpointRequest.spec:type_name -> atelet.WorkloadSpec
	0,  // 10: atelet.CheckpointRequest.type:type_name -> atelet.CheckpointType
	10, // 11: atelet.CheckpointRequest.local_config:type_name -> atelet.LocalCheckpointConfiguration
	11, // 12: atelet.CheckpointRequest.external_config:type_name -> atelet.ExternalCheckpointConfiguration
	5,  // 13: atelet.RestoreRequest.runsc:type_name -> atelet.RunscConfig
	6,  // 14: atelet.RestoreRequest.spec:type_name -> atelet.WorkloadSpec
	0,  // 15: atelet.RestoreRequest.type:type_name -> atelet.CheckpointType
	10, // 16: atelet.RestoreRequest.local_config:type_name -> atelet.LocalCheckpointConfiguration
	11, // 17: atelet.RestoreRequest.external_config:type_name -> atelet.ExternalCheckpointConfiguration
	1,  // 18: atelet.AteomHerder.Run:input_type -> atelet.RunRequest
	12, // 19: atelet.AteomHerder.Checkpoint:input_type -> atelet.CheckpointRequest
	14, // 20: atelet.AteomHerder.Restore:input_type -> atelet.RestoreRequest
	9,  // 21: atelet.AteomHerder.Run:output_type -> atelet.RunResponse
	13, // 22: atelet.AteomHerder.Checkpoint:output_type -> atelet.CheckpointResponse
	15, // 23: atelet.AteomHerder.Restore:output_type -> atelet.RestoreResponse
	21, // [21:24] is the sub-list for method output_type
	18, // [18:21] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_atelet_proto_init() }
func file_atelet_proto_init() {
	if File_atelet_proto != nil {
		return
	}
	file_atelet_proto_msgTypes[11].OneofWrappers = []any{
		(*CheckpointRequest_LocalConfig)(nil),
		(*CheckpointRequest_ExternalConfig)(nil),
	}
	file_atelet_proto_msgTypes[13].OneofWrappers = []any{
		(*RestoreRequest_LocalConfig)(nil),
		(*RestoreRequest_ExternalConfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atelet_proto_rawDesc), len(file_atelet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_atelet_proto_goTypes,
		DependencyIndexes: file_atelet_proto_depIdxs,
		EnumInfos:         file_atelet_proto_enumTypes,
		MessageInfos:      file_atelet_proto_msgTypes,
	}.Build()
	File_atelet_proto = out.File
	file_atelet_proto_goTypes = nil
	file_atelet_proto_depIdxs = nil
}
