# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../ate-api-server.yaml
  - ../ate-controller.yaml
  - ./atelet
  - ../atenet-dns.yaml
  - ../atenet-router.yaml
  - ../valkey.yaml
  - ../pod-certificate-controller.yaml
  - rustfs.yaml
  - ./otel-collector.yaml
  - ./prometheus.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ate-api-server-deployment
      namespace: ate-system
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://opentelemetry-collector.otel-system.svc:4317
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "--csi-controller-endpoints=tcp://csi-hostpath-controller.default.svc:50051,tcp://csi-nfs-controller.kube-system.svc:50052"
  - patch: |-
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: atelet
        namespace: ate-system
      spec:
        template:
          spec:
            containers:
            - name: atelet
              env:
              - name: OTEL_EXPORTER_OTLP_ENDPOINT
                value: http://opentelemetry-collector.otel-system.svc:4317

